apiVersion: v1
kind: Service
metadata:
  name: affine-cloud
spec:
  type: NodePort
  selector:
    app: affine-cloud
  ports:
  - name: affine-cloud
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
