apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudflared
spec:
    selector:
        matchLabels:
            app: cloudflared
    replicas: 1
    template:
        metadata:
            labels:
                app: cloudflared
        spec:
            containers:
                - name: cloudflared
                  image: 'cloudflare/cloudflared:{{ .Values.cloudflared.tag | default .Chart.AppVersion }}'
                  imagePullPolicy: Always
                  args: ['tunnel', '--no-autoupdate', '--metrics=localhost:2000', 'run', '--token=$(token)']
                  env:
                      - name: token
                        valueFrom:
                            secretKeyRef:
                                name: cloudflared
                                key: token
                  livenessProbe:
                      httpGet:
                          path: /ready
                          port: 2000
                      failureThreshold: 1
                      initialDelaySeconds: 10
                      periodSeconds: 10
                  resources:
                      limits:
                          cpu: '{{ .Values.cloudflared.resources.cpu }}'
                          ephemeral-storage: '{{ .Values.cloudflared.resources.ephemeralStorage }}'
                          memory: '{{ .Values.cloudflared.resources.memory }}'
